### PR TITLE
Project Cards

### LINKED ISSUE #3: Projects Component

### PR DESCRIPTION
**Pull request by knarfamlap**
Adds project cards using the react-bootstrap library and additional libraries for icons. Cards still need to be placed in a grid ordered.

### CODE REVIEW

**Comment by knarfamlap** [comment]
This PR still not ready. I will update it in a few hours.

**Comment by knarfamlap** [comment]
Ready to be reviewed/merged.

**Comment by knarfamlap** [comment]
Screen Shot 2021-01-28 at 10 23 13 AM

**Review by ensardogrusoz — APPROVED** [review]

**Comment by bhassan6621** [comment]
LGTM!

**Review by bhassan6621 — APPROVED** [review]

**Review by JaJiang316 — APPROVED** [review]
LGTM

**Comment by ensardogrusoz** [comment]
Screen Shot 2021-01-30 at 12 50 19 PM

how come the images dont show when i run it

**Pull request merged**
